version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sicredi-postgres
    environment:
      POSTGRES_DB: sicredi_db
      POSTGRES_USER: sicredi
      POSTGRES_PASSWORD: sicredi123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sicredi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sicredi -d sicredi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sicredi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sicredi-network
    command: redis-server --appendonly yes --requirepass redis123
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  sicredi-network:
    driver: bridge